import React, { useState } from 'react';
import { api } from '../context/AuthContext';
import { PrimaryButton } from './AdminUI';
import { Plus, Trash2, Save, FileText, Sparkles } from 'lucide-react';

const AssessmentCreator = () => {
  const [title, setTitle] = useState('');
  const [questions, setQuestions] = useState([
    { question: '', options: ['', '', '', ''], correctOption: '' }
  ]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  
  // AI Generation State
  const [aiModalOpen, setAiModalOpen] = useState(false);
  const [aiTopic, setAiTopic] = useState('');
  const [aiGenerating, setAiGenerating] = useState(false);

  const handleGenerateAI = async () => {
    if (!aiTopic.trim()) return;
    setAiGenerating(true);
    try {
      const res = await api.post('/ai/generate-assessment', { topic: aiTopic });
      if (res.data.success) {
        setQuestions(res.data.data);
        setTitle(aiTopic);
        setAiModalOpen(false);
        setMessage('Assessment successfully generated by AI!');
      }
    } catch (err) {
      alert(err.response?.data?.error || 'Failed to generate assessment with AI.');
    } finally {
      setAiGenerating(false);
    }
  };

  const addQuestion = () => {
    setQuestions([...questions, { question: '', options: ['', '', '', ''], correctOption: '' }]);
  };

  const removeQuestion = (index) => {
    setQuestions(questions.filter((_, i) => i !== index));
  };

  const handleQuestionChange = (index, field, value) => {
    const updated = [...questions];
    updated[index][field] = value;
    setQuestions(updated);
  };

  const handleOptionChange = (qIndex, oIndex, value) => {
    const updated = [...questions];
    updated[qIndex].options[oIndex] = value;
    setQuestions(updated);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setLoading(true);
      setMessage('');
      
      // Validation
      if (!title) return setMessage('Assessment title is required.');
      for (const q of questions) {
        if (!q.question) return setMessage('All questions must have text.');
        if (q.options.some(opt => !opt)) return setMessage('All options must be filled.');
        if (!q.correctOption) return setMessage('Each question must have a correct option selected.');
        if (!q.options.includes(q.correctOption)) return setMessage('Correct option must match one of the provided options exactly.');
      }

      const res = await api.post('/assessment-templates', { title, questions });
      if (res.data.success) {
        setMessage('Assessment Template created successfully!');
        setTitle('');
        setQuestions([{ question: '', options: ['', '', '', ''], correctOption: '' }]);
      }
    } catch (err) {
      setMessage(err.response?.data?.error || 'Failed to create assessment.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-3">
          <div className="p-2 bg-brand-50 text-brand-600 rounded-xl">
            <FileText size={20} />
          </div>
          <h2 className="text-xl font-bold text-slate-800">Create New Assessment</h2>
        </div>
        <button
          onClick={() => setAiModalOpen(true)}
          className="flex items-center space-x-2 px-4 py-2 bg-gradient-to-r from-violet-500 to-fuchsia-500 hover:from-violet-600 hover:to-fuchsia-600 text-white rounded-xl text-sm font-bold transition-all shadow-md shadow-violet-500/20"
        >
          <Sparkles size={16} /> <span>Generate with Gemini</span>
        </button>
      </div>

      {message && (
        <div className={`p-4 mb-6 rounded-xl text-sm font-semibold ${message.includes('successfully') ? 'bg-emerald-50 text-emerald-600 border border-emerald-200' : 'bg-rose-50 text-rose-600 border border-rose-200'}`}>
          {message}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-8">
        <div>
          <label className="block text-sm font-semibold text-slate-700 mb-2">Assessment Title / Subject</label>
          <input 
            type="text" 
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-brand-500/20 outline-none"
            placeholder="e.g., Advanced Database Concepts"
          />
        </div>

        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-bold text-slate-800">Questions</h3>
            <button 
              type="button" 
              onClick={addQuestion}
              className="flex items-center space-x-2 px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg text-sm font-semibold transition-colors"
            >
              <Plus size={16} /> <span>Add Question</span>
            </button>
          </div>

          {questions.map((q, qIndex) => (
            <div key={qIndex} className="p-5 border border-slate-200 rounded-2xl bg-slate-50 space-y-4 relative">
              {questions.length > 1 && (
                <button 
                  type="button" 
                  onClick={() => removeQuestion(qIndex)}
                  className="absolute top-4 right-4 text-slate-400 hover:text-rose-500 transition-colors"
                >
                  <Trash2 size={18} />
                </button>
              )}
              
              <div>
                <label className="block text-xs font-semibold text-slate-600 mb-1">Question {qIndex + 1}</label>
                <input 
                  type="text" 
                  value={q.question}
                  onChange={(e) => handleQuestionChange(qIndex, 'question', e.target.value)}
                  className="w-full p-2.5 bg-white border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-brand-500/20 outline-none"
                  placeholder="Enter your question here..."
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {q.options.map((opt, oIndex) => (
                  <div key={oIndex}>
                    <label className="block text-xs font-medium text-slate-500 mb-1">Option {oIndex + 1}</label>
                    <input 
                      type="text" 
                      value={opt}
                      onChange={(e) => handleOptionChange(qIndex, oIndex, e.target.value)}
                      className="w-full p-2 bg-white border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-brand-500/20 outline-none"
                      placeholder={`Option ${oIndex + 1}`}
                    />
                  </div>
                ))}
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-600 mb-1">Correct Option (Select one of the above)</label>
                <select
                  value={q.correctOption}
                  onChange={(e) => handleQuestionChange(qIndex, 'correctOption', e.target.value)}
                  className="w-full p-2.5 bg-white border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-brand-500/20 outline-none"
                >
                  <option value="">-- Select Correct Option --</option>
                  {q.options.map((opt, oIndex) => (
                    opt.trim() !== '' && <option key={oIndex} value={opt}>{opt}</option>
                  ))}
                </select>
              </div>
            </div>
          ))}
        </div>

        <div className="flex justify-end pt-4 border-t border-slate-100">
          <PrimaryButton type="submit" disabled={loading}>
            <Save size={18} />
            <span>{loading ? 'Saving...' : 'Save Assessment Template'}</span>
          </PrimaryButton>
        </div>
      </form>

      {aiModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50">
          <div className="bg-white p-6 rounded-2xl shadow-xl w-full max-w-md">
            <div className="flex items-center space-x-2 mb-4">
              <Sparkles className="text-violet-500" size={24} />
              <h3 className="text-lg font-bold text-slate-800">Generate with Gemini</h3>
            </div>
            <p className="text-sm text-slate-500 mb-4">Enter a topic and Gemini will automatically generate 5 multiple-choice questions with answers.</p>
            <input 
              type="text"
              value={aiTopic}
              onChange={(e) => setAiTopic(e.target.value)}
              placeholder="e.g. Advanced React Hooks"
              className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl mb-4 focus:ring-2 focus:ring-violet-500/20 outline-none"
              autoFocus
            />
            <div className="flex justify-end gap-3">
              <button onClick={() => setAiModalOpen(false)} className="px-4 py-2 text-slate-600 font-semibold hover:bg-slate-100 rounded-xl transition-colors text-sm">Cancel</button>
              <button 
                onClick={handleGenerateAI}
                disabled={aiGenerating || !aiTopic.trim()}
                className="px-4 py-2 bg-violet-500 hover:bg-violet-600 text-white rounded-xl font-semibold text-sm transition-colors shadow-md shadow-violet-500/20 disabled:opacity-50"
              >
                {aiGenerating ? 'Generating...' : 'Generate Questions'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AssessmentCreator;
